//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkToLog.Bot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitErrorRatioPerIPAndHour1
    {
        public System.DateTime st { get; set; }
        public int hour { get; set; }
        public string sIP { get; set; }
        public Nullable<long> NormalRequests { get; set; }
        public Nullable<long> Errors { get; set; }
    }
}
