//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkToLog.Bot.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogDbContext : DbContext
    {
        public LogDbContext()
            : base("name=LogDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HitErrorRatioPerIPAndHour1> HitErrorRatioPerIPAndHour1 { get; set; }
        public virtual DbSet<SparkSummary> SparkSummaries { get; set; }
        public virtual DbSet<Top20AverageLongestRequests> Top20AverageLongestRequests { get; set; }
        public virtual DbSet<Top20AverageLongestRequests1> Top20AverageLongestRequests1 { get; set; }
        public virtual DbSet<Top20HitURLs> Top20HitURLs { get; set; }
        public virtual DbSet<Top20HitURLs1> Top20HitURLs1 { get; set; }
        public virtual DbSet<UniqClientIPsPerHour> UniqClientIPsPerHours { get; set; }
    }
}
