//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkToLog.Bot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top20AverageLongestRequests
    {
        public Nullable<System.DateTime> st { get; set; }
        public string csURI { get; set; }
        public long Count { get; set; }
        public Nullable<double> scbytes { get; set; }
        public Nullable<double> csbytes { get; set; }
        public Nullable<int> MinTime { get; set; }
        public Nullable<int> MaxTime { get; set; }
        public Nullable<double> AvgTime { get; set; }
    }
}
