//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkToLog.Bot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqClientIPsPerHour
    {
        public Nullable<System.DateTime> st { get; set; }
        public Nullable<int> hour { get; set; }
        public long cnt { get; set; }
    }
}
